name: 'Required Task Completed Checker'
description: 'An action that checks if tasks marked as required have been completed'
author: 'kentaro-m (forked by macqueenism)'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
branding:
  icon: 'check-square'
  color: 'green'
