name: Test
on:
  push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: yarn install, build, lint and test
      run: |
        yarn install
        yarn run build
        yarn run lint
        yarn test
